import { Product, Category, Brand, HomepageBanner } from '../types';

export const MOCK_CATEGORIES: (Category & { icon?: string; itemCount?: number; color?: string })[] = [
  {
    id: 1,
    name: 'Remote Control & Cars',
    slug: 'remote-control',
    description: 'High-speed RC cars, stunt tumblers, drift racers and flying helicopters.',
    imageUrl: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=500&q=80',
    image_url: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=500&q=80',
    display_order: 1,
    is_active: 1,
    icon: '🚗',
    itemCount: 42,
    color: 'from-orange-500 to-amber-500'
  },
  {
    id: 2,
    name: 'Building Blocks & LEGO',
    slug: 'building-blocks',
    description: 'Interlocking bricks, architectural sets, magnetic blocks and engineering kits.',
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=500&q=80',
    image_url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=500&q=80',
    display_order: 2,
    is_active: 1,
    icon: '🏰',
    itemCount: 56,
    color: 'from-red-500 to-orange-500'
  },
  {
    id: 3,
    name: 'STEM & Science Toys',
    slug: 'educational-toys',
    description: 'Robotics kits, solar projects, chemistry labs, and educational brain boosters.',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=500&q=80',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=500&q=80',
    display_order: 3,
    is_active: 1,
    icon: '🔬',
    itemCount: 38,
    color: 'from-blue-600 to-cyan-500'
  },
  {
    id: 4,
    name: 'Plush & Soft Toys',
    slug: 'soft-toys',
    description: 'Giant cuddly teddy bears, baby-safe plushies, and huggable cartoon animals.',
    imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=500&q=80',
    image_url: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=500&q=80',
    display_order: 4,
    is_active: 1,
    icon: '🧸',
    itemCount: 34,
    color: 'from-pink-500 to-rose-400'
  },
  {
    id: 5,
    name: 'Dolls & Playsets',
    slug: 'dolls-playsets',
    description: 'Fashion dolls, magical princess sets, dream dollhouses, and vanity kits.',
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=500&q=80',
    image_url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=500&q=80',
    display_order: 5,
    is_active: 1,
    icon: '👑',
    itemCount: 29,
    color: 'from-purple-500 to-pink-500'
  },
  {
    id: 6,
    name: 'Action Figures & Heroes',
    slug: 'action-figures',
    description: 'Superhero legends, anime champions, robotic transformers, and collectables.',
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=500&q=80',
    image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=500&q=80',
    display_order: 6,
    is_active: 1,
    icon: '⚡',
    itemCount: 45,
    color: 'from-indigo-600 to-blue-500'
  },
  {
    id: 7,
    name: 'Board Games & Puzzles',
    slug: 'board-games',
    description: 'Family strategy board games, wooden puzzles, Monopoly, and memory games.',
    imageUrl: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=500&q=80',
    image_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=500&q=80',
    display_order: 7,
    is_active: 1,
    icon: '🎲',
    itemCount: 50,
    color: 'from-emerald-500 to-teal-600'
  },
  {
    id: 8,
    name: 'Art, Craft & Dough',
    slug: 'art-craft',
    description: 'Modeling dough, pottery studio sets, coloring kits, and creative DIY crafts.',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=500&q=80',
    image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=500&q=80',
    display_order: 8,
    is_active: 1,
    icon: '🎨',
    itemCount: 27,
    color: 'from-amber-500 to-yellow-400'
  },
  {
    id: 9,
    name: 'Outdoor, Sports & Blasters',
    slug: 'outdoor-sports',
    description: 'Foam blasters, foldable scooters, basketball sets, and active outdoor gear.',
    imageUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=500&q=80',
    image_url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=500&q=80',
    display_order: 9,
    is_active: 1,
    icon: '🎯',
    itemCount: 31,
    color: 'from-cyan-600 to-blue-600'
  },
  {
    id: 10,
    name: 'Baby & Toddler Sensory',
    slug: 'baby-toys',
    description: 'Non-toxic musical rattles, sensory teething rings, and soft activity gyms.',
    imageUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=500&q=80',
    image_url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=500&q=80',
    display_order: 10,
    is_active: 1,
    icon: '👶',
    itemCount: 24,
    color: 'from-teal-400 to-emerald-500'
  }
];

export const MOCK_BRANDS: Brand[] = [
  { id: 1, name: 'LEGO', slug: 'lego', description: 'Iconic construction brick systems', display_order: 1, is_active: 1 },
  { id: 2, name: 'Hot Wheels', slug: 'hot-wheels', description: 'High-speed die-cast vehicles & tracks', display_order: 2, is_active: 1 },
  { id: 3, name: 'Barbie', slug: 'barbie', description: 'Inspiring fashion dolls & dreamhouses', display_order: 3, is_active: 1 },
  { id: 4, name: 'Nerf', slug: 'nerf', description: 'Foam blasters & active sports toys', display_order: 4, is_active: 1 },
  { id: 5, name: 'Funskool', slug: 'funskool', description: 'Premier Indian toy manufacturer', display_order: 5, is_active: 1 },
  { id: 6, name: 'Hasbro', slug: 'hasbro-gaming', description: 'World-renowned family board games', display_order: 6, is_active: 1 },
  { id: 7, name: 'Fisher-Price', slug: 'fisher-price', description: 'Early childhood development toys', display_order: 7, is_active: 1 },
  { id: 8, name: 'Play-Doh', slug: 'play-doh', description: 'Creative non-toxic modeling compound', display_order: 8, is_active: 1 },
];

export const MOCK_BANNERS: HomepageBanner[] = [
  {
    id: 1,
    title: 'Welcome to India’s Favorite Toy Wonderland!',
    subtitle: 'Over 1,000+ BIS safety-certified toys delivered directly to your doorstep with love.',
    imageUrl: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=1600&q=80',
    mobileImageUrl: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=800&q=80',
    link: '/shop',
    cta_text: 'Explore Collection',
    displayOrder: 1,
    is_active: true,
  },
  {
    id: 2,
    title: 'High-Octane RC Stunt Racers & Drones',
    subtitle: 'Unstoppable 360° flips, LED wheels, and rechargeable fast-action thrill machines.',
    imageUrl: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=1600&q=80',
    mobileImageUrl: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
    link: '/category/remote-control',
    cta_text: 'Shop RC Cars',
    displayOrder: 2,
    is_active: true,
  },
  {
    id: 3,
    title: 'Ignite Young Minds with STEM Robotics',
    subtitle: 'Hands-on science kits, solar-powered inventions, and future-ready coding toys.',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1600&q=80',
    mobileImageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    link: '/category/educational-toys',
    cta_text: 'Discover STEM',
    displayOrder: 3,
    is_active: true,
  }
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    slug: '360-stunt-tumbler-rechargeable-rc-car',
    name: '360° Stunt Tumbler Rechargeable RC Car with LED Wheels',
    sku: 'RC-STUNT-360',
    category_id: 1,
    category_name: 'Remote Control & Cars',
    brand_id: 5,
    brand_name: 'Funskool',
    short_description: 'Double-sided 360° flip stunt car with bright neon lights and 2.4GHz remote controller.',
    description: 'Experience unstoppable stunt action! This rechargeable RC car flips, tumbles, and drives on both sides. Equipped with rubber off-road tires, vivid LED wheel illuminations, and USB fast charging.',
    price: 899,
    selling_price: 899,
    mrp: 1499,
    discountPercentage: 40,
    discount_percentage: 40,
    stock: 24,
    stock_quantity: 24,
    rating: 4.9,
    reviewCount: 48,
    is_featured: 1,
    is_bestseller: 1,
    is_new_arrival: 1,
    is_offer: 1,
    ageGroup: '6-8',
    age_group: '6-8',
    images: [
      { id: 101, url: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80', alt: '360 Stunt RC Car', isPrimary: true },
      { id: 102, url: 'https://images.unsplash.com/photo-1558865869-c93f6f8482af?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1558865869-c93f6f8482af?auto=format&fit=crop&w=800&q=80', alt: 'RC Stunt in motion', isPrimary: false }
    ],
    variants: [
      { id: 11, name: 'Neon Blue', variant_type: 'Color', variant_value: 'Blue', price: 899, mrp: 1499, selling_price: 899, stock_quantity: 14, is_available: 1 },
      { id: 12, name: 'Fiery Orange', variant_type: 'Color', variant_value: 'Orange', price: 899, mrp: 1499, selling_price: 899, stock_quantity: 10, is_available: 1 }
    ]
  },
  {
    id: 2,
    slug: 'lego-classic-creative-starter-bricks',
    name: 'LEGO Classic Creative Starter Bricks Box (480 Pieces)',
    sku: 'LGO-CLSC-480',
    category_id: 2,
    category_name: 'Building Blocks & LEGO',
    brand_id: 1,
    brand_name: 'LEGO',
    short_description: '480 colorful original LEGO building bricks with doors, windows, wheels and eyes.',
    description: 'Unleash limitless imagination with genuine LEGO bricks in 33 vibrant colors. Build castles, airplanes, vehicles, cute animals, and fantastic creatures. Perfect for motor skill development.',
    price: 1199,
    selling_price: 1199,
    mrp: 1499,
    discountPercentage: 20,
    discount_percentage: 20,
    stock: 18,
    stock_quantity: 18,
    rating: 4.9,
    reviewCount: 82,
    is_featured: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
    ageGroup: '4-8',
    age_group: '4-8',
    images: [
      { id: 201, url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80', alt: 'LEGO Classic Set', isPrimary: true },
      { id: 202, url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80', alt: 'Building Bricks Assortment', isPrimary: false }
    ]
  },
  {
    id: 3,
    slug: '12-in-1-educational-solar-robot-creation-kit',
    name: '12-in-1 STEM Solar Powered Robotics Engineering Kit',
    sku: 'STEM-SLR-12',
    category_id: 3,
    category_name: 'STEM & Science Toys',
    brand_id: 5,
    brand_name: 'Funskool',
    short_description: 'Build 12 distinct working robots powered entirely by direct sunlight or halogen light.',
    description: 'Introduce kids to green energy, mechanical gears, and robotics! Assemble land bots, turtle bots, boat crawlers, and rover walkers without requiring any batteries. Comes with a clear step-by-step blueprint guide.',
    price: 1299,
    selling_price: 1299,
    mrp: 1799,
    discountPercentage: 28,
    discount_percentage: 28,
    stock: 15,
    stock_quantity: 15,
    rating: 4.8,
    reviewCount: 39,
    is_featured: 1,
    is_bestseller: 1,
    is_new_arrival: 1,
    ageGroup: '8-12',
    age_group: '8-12',
    images: [
      { id: 301, url: 'https://images.unsplash.com/photo-1535378917042-10a22c95931a?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1535378917042-10a22c95931a?auto=format&fit=crop&w=800&q=80', alt: 'STEM Solar Robot Kit', isPrimary: true }
    ]
  },
  {
    id: 4,
    slug: 'giant-plush-cuddly-teddy-bear-3-feet',
    name: 'Ultra-Soft Cuddly Giant Plush Teddy Bear (3 Feet / 90cm)',
    sku: 'PLSH-TEDDY-90',
    category_id: 4,
    category_name: 'Plush & Soft Toys',
    brand_id: 5,
    brand_name: 'Funskool',
    short_description: 'Hypoallergenic super-soft huggable plush teddy bear with embroidered paws and bow.',
    description: 'Made from premium non-shedding fur and 100% virgin PP cotton filling. Washable, skin-friendly, and the ultimate birthday or celebration surprise gift for children of all ages.',
    price: 999,
    selling_price: 999,
    mrp: 1699,
    discountPercentage: 41,
    discount_percentage: 41,
    stock: 30,
    stock_quantity: 30,
    rating: 5.0,
    reviewCount: 64,
    is_featured: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
    is_offer: 1,
    ageGroup: '0-2',
    age_group: '0-2',
    images: [
      { id: 401, url: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=800&q=80', alt: 'Giant Plush Teddy Bear', isPrimary: true },
      { id: 402, url: 'https://images.unsplash.com/photo-1556012018-50c5c0da73bf?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1556012018-50c5c0da73bf?auto=format&fit=crop&w=800&q=80', alt: 'Plush Toy Family', isPrimary: false }
    ],
    variants: [
      { id: 41, name: 'Honey Brown', variant_type: 'Color', variant_value: 'Brown', price: 999, mrp: 1699, selling_price: 999, stock_quantity: 18, is_available: 1 },
      { id: 42, name: 'Snow Cream', variant_type: 'Color', variant_value: 'Cream', price: 999, mrp: 1699, selling_price: 999, stock_quantity: 12, is_available: 1 }
    ]
  },
  {
    id: 5,
    slug: 'barbie-deluxe-fairy-tale-princess-tiara',
    name: 'Barbie Deluxe Fairy Tale Sparkle Princess Doll with Royal Tiara',
    sku: 'BRB-PRNC-002',
    category_id: 5,
    category_name: 'Dolls & Playsets',
    brand_id: 3,
    brand_name: 'Barbie',
    short_description: 'Glitter gown fashion doll with brushable locks, sparkling crown and fairy shoes.',
    description: 'Inspire magical storytelling with this authentic Mattel Barbie Princess doll. Features a shimmering ombre painted bodice, removable galaxy skirt, royal tiara, and matching heels for royal balls.',
    price: 749,
    selling_price: 749,
    mrp: 999,
    discountPercentage: 25,
    discount_percentage: 25,
    stock: 22,
    stock_quantity: 22,
    rating: 4.8,
    reviewCount: 52,
    is_featured: 1,
    is_bestseller: 0,
    is_new_arrival: 1,
    ageGroup: '3-5',
    age_group: '3-5',
    images: [
      { id: 501, url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80', alt: 'Barbie Deluxe Princess Doll', isPrimary: true }
    ]
  },
  {
    id: 6,
    slug: 'hot-wheels-5-car-collector-multi-pack',
    name: 'Hot Wheels 5-Car High Speed Collector Multi-Pack',
    sku: 'HW-PACK-5',
    category_id: 1,
    category_name: 'Remote Control & Cars',
    brand_id: 2,
    brand_name: 'Hot Wheels',
    short_description: 'Five 1:64 scale die-cast speed machines with aerodynamic styling and custom track wheels.',
    description: 'The ultimate gift pack for miniature speed enthusiasts! Authentic detailing, durable metal body construction, smooth rolling axles, and compatibility with all official Hot Wheels stunt tracks.',
    price: 699,
    selling_price: 699,
    mrp: 849,
    discountPercentage: 18,
    discount_percentage: 18,
    stock: 45,
    stock_quantity: 45,
    rating: 4.9,
    reviewCount: 91,
    is_featured: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
    ageGroup: '3-5',
    age_group: '3-5',
    images: [
      { id: 601, url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80', alt: 'Hot Wheels 5-Pack', isPrimary: true }
    ]
  },
  {
    id: 7,
    slug: 'hasbro-monopoly-india-edition-board-game',
    name: 'Hasbro Monopoly Deluxe India Edition Family Board Game',
    sku: 'HBR-MNP-IND',
    category_id: 7,
    category_name: 'Board Games & Puzzles',
    brand_id: 6,
    brand_name: 'Hasbro',
    short_description: 'Classic property trading board game featuring India’s top iconic cities, cards & tokens.',
    description: 'Gather the whole family for legendary board game nights! Buy, sell, trade, and mortgage properties across Mumbai, Delhi, Bengaluru, and Kolkata. Includes metallic tokens, cards, houses, and banknotes.',
    price: 999,
    selling_price: 999,
    mrp: 1299,
    discountPercentage: 23,
    discount_percentage: 23,
    stock: 19,
    stock_quantity: 19,
    rating: 4.9,
    reviewCount: 76,
    is_featured: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
    ageGroup: '8-12',
    age_group: '8-12',
    images: [
      { id: 701, url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80', alt: 'Monopoly Board Game', isPrimary: true }
    ]
  },
  {
    id: 8,
    slug: 'nerf-elite-commander-foam-dart-blaster',
    name: 'Nerf Elite 2.0 Commander 6-Dart Rotating Drum Blaster',
    sku: 'NRF-CMD-001',
    category_id: 9,
    category_name: 'Outdoor, Sports & Blasters',
    brand_id: 4,
    brand_name: 'Nerf',
    short_description: 'Rapid-fire foam blaster with 6-dart cylinder and 12 official Nerf safety darts included.',
    description: 'Gear up for epic outdoor target battles! Fires darts up to 90 feet (27 meters). Includes slam-fire capability, tactical accessory rails, and stock/barrel attachment points for full tactical customization.',
    price: 1149,
    selling_price: 1149,
    mrp: 1499,
    discountPercentage: 23,
    discount_percentage: 23,
    stock: 16,
    stock_quantity: 16,
    rating: 4.8,
    reviewCount: 35,
    is_featured: 0,
    is_bestseller: 1,
    is_new_arrival: 1,
    ageGroup: '8-12',
    age_group: '8-12',
    images: [
      { id: 801, url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80', alt: 'Nerf Foam Blaster', isPrimary: true }
    ]
  },
  {
    id: 9,
    slug: 'play-doh-kitchen-creations-deluxe-chef-set',
    name: 'Play-Doh Kitchen Creations Deluxe Pretend Cooking Studio',
    sku: 'PD-KTCH-003',
    category_id: 8,
    category_name: 'Art, Craft & Dough',
    brand_id: 8,
    brand_name: 'Play-Doh',
    short_description: '8 colorful non-toxic clay cans, sizzle stove, noodle extruder, and 20+ kitchen tools.',
    description: 'Little chefs can whip up imaginary burgers, pizzas, colorful noodles, and sweet cookies. The battery-free sizzle stove makes fun realistic sounds when child presses a pan onto the burner!',
    price: 799,
    selling_price: 799,
    mrp: 1099,
    discountPercentage: 27,
    discount_percentage: 27,
    stock: 28,
    stock_quantity: 28,
    rating: 4.7,
    reviewCount: 42,
    is_featured: 1,
    is_bestseller: 0,
    is_new_arrival: 1,
    ageGroup: '3-5',
    age_group: '3-5',
    images: [
      { id: 901, url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80', alt: 'Play-Doh Kitchen Studio', isPrimary: true }
    ]
  },
  {
    id: 10,
    slug: 'magnetic-building-tiles-60-pieces-set',
    name: 'MagnoSpark 3D Magnetic Geometric Tiles (60 Pcs Discovery Set)',
    sku: 'MAG-TILE-60',
    category_id: 2,
    category_name: 'Building Blocks & LEGO',
    brand_id: 5,
    brand_name: 'Funskool',
    short_description: 'Translucent magnetic tiles with strong neodymium magnets for 3D castles and shapes.',
    description: 'STEM-certified tactile learning! Build castles, towers, spheres, and rocket ships. High-durability food-grade ultrasonic welded ABS plastic with round edges prevents scratching.',
    price: 1399,
    selling_price: 1399,
    mrp: 1999,
    discountPercentage: 30,
    discount_percentage: 30,
    stock: 20,
    stock_quantity: 20,
    rating: 4.9,
    reviewCount: 57,
    is_featured: 1,
    is_bestseller: 1,
    is_new_arrival: 1,
    is_offer: 1,
    ageGroup: '3-5',
    age_group: '3-5',
    images: [
      { id: 1001, url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80', alt: 'Magnetic Tiles', isPrimary: true }
    ]
  },
  {
    id: 11,
    slug: 'marvel-avengers-iron-man-talking-action-figure',
    name: 'Marvel Avengers Titan Hero Series Iron Man with Light Arc-Reactor',
    sku: 'MVL-IRN-12',
    category_id: 6,
    category_name: 'Action Figures & Heroes',
    brand_id: 6,
    brand_name: 'Hasbro',
    short_description: '12-inch poseable Iron Man action figure with chest light and repulsor battle sound effects.',
    description: 'Blast into battle with Tony Stark’s armor! Features 7 articulation points for superhero poses, voice button with iconic dialogue quotes, and glowing chest beam.',
    price: 1099,
    selling_price: 1099,
    mrp: 1499,
    discountPercentage: 27,
    discount_percentage: 27,
    stock: 14,
    stock_quantity: 14,
    rating: 4.8,
    reviewCount: 31,
    is_featured: 1,
    is_bestseller: 0,
    is_new_arrival: 1,
    ageGroup: '6-8',
    age_group: '6-8',
    images: [
      { id: 1101, url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80', alt: 'Iron Man Action Figure', isPrimary: true }
    ]
  },
  {
    id: 12,
    slug: 'fisher-price-kick-play-piano-musical-gym',
    name: 'Fisher-Price Deluxe Kick & Play Piano Musical Activity Gym',
    sku: 'FSH-GYM-001',
    category_id: 10,
    category_name: 'Baby & Toddler Sensory',
    brand_id: 7,
    brand_name: 'Fisher-Price',
    short_description: 'Sensory baby play mat with light-up piano keys, overhead arch, mirror and 5 rattle toys.',
    description: 'Grows with baby through 4 stages: Lay & play, Tummy time, Sit & play, and Take-along music. Smart Stages technology changes learning content as your infant grows.',
    price: 2199,
    selling_price: 2199,
    mrp: 2999,
    discountPercentage: 27,
    discount_percentage: 27,
    stock: 9,
    stock_quantity: 9,
    rating: 5.0,
    reviewCount: 44,
    is_featured: 1,
    is_bestseller: 1,
    is_new_arrival: 0,
    ageGroup: '0-2',
    age_group: '0-2',
    images: [
      { id: 1201, url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80', alt: 'Baby Musical Gym', isPrimary: true }
    ]
  },
  {
    id: 13,
    slug: 'wooden-rainbow-stacker-montessori-toy',
    name: 'Montessori Organic Wooden Rainbow Arch Stacker (12 Arches)',
    sku: 'MNT-WOD-RNW',
    category_id: 3,
    category_name: 'STEM & Science Toys',
    brand_id: 5,
    brand_name: 'Funskool',
    short_description: 'Eco-friendly natural wood nesting rainbow blocks finished with organic water-based dyes.',
    description: 'Encourage open-ended Montessori play! Kids can construct tunnels, bridges, doll cradles, and abstract sculptures. Helps spatial awareness and fine motor coordination.',
    price: 849,
    selling_price: 849,
    mrp: 1199,
    discountPercentage: 29,
    discount_percentage: 29,
    stock: 22,
    stock_quantity: 22,
    rating: 4.9,
    reviewCount: 38,
    is_featured: 0,
    is_bestseller: 1,
    is_new_arrival: 1,
    is_offer: 1,
    ageGroup: '0-2',
    age_group: '0-2',
    images: [
      { id: 1301, url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80', alt: 'Wooden Rainbow Stacker', isPrimary: true }
    ]
  },
  {
    id: 14,
    slug: 'high-speed-foldable-led-kick-scooter',
    name: 'Speedster 3-Wheel Lean-to-Steer Scooter with Flashing LED Wheels',
    sku: 'SCT-3W-LED',
    category_id: 9,
    category_name: 'Outdoor, Sports & Blasters',
    brand_id: 5,
    brand_name: 'Funskool',
    short_description: 'Adjustable 4-height handlebar scooter with wide anti-slip deck and magnetic light-up wheels.',
    description: 'Safe, ultra-stable 3-wheel design engineered for kids. Lean-to-steer technology fosters balance and coordination. Folds in 2 seconds for hassle-free trunk travel.',
    price: 1899,
    selling_price: 1899,
    mrp: 2699,
    discountPercentage: 30,
    discount_percentage: 30,
    stock: 12,
    stock_quantity: 12,
    rating: 4.8,
    reviewCount: 29,
    is_featured: 1,
    is_bestseller: 0,
    is_new_arrival: 1,
    ageGroup: '3-5',
    age_group: '3-5',
    images: [
      { id: 1401, url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80', alt: 'Kids LED Scooter', isPrimary: true }
    ],
    variants: [
      { id: 141, name: 'Cyber Blue', variant_type: 'Color', variant_value: 'Blue', price: 1899, mrp: 2699, selling_price: 1899, stock_quantity: 7, is_available: 1 },
      { id: 142, name: 'Bubble Pink', variant_type: 'Color', variant_value: 'Pink', price: 1899, mrp: 2699, selling_price: 1899, stock_quantity: 5, is_available: 1 }
    ]
  },
  {
    id: 15,
    slug: '1000-piece-ancient-world-map-jigsaw-puzzle',
    name: 'Mastermind 1000-Piece Vintage World Map Family Jigsaw Puzzle',
    sku: 'PZL-1000-MAP',
    category_id: 7,
    category_name: 'Board Games & Puzzles',
    brand_id: 5,
    brand_name: 'Funskool',
    short_description: 'Precision cut recycled cardboard puzzle with glare-free matte finish and bonus poster.',
    description: 'An engrossing challenge for teens, adults, and families! Learn geography, continents, and antique maritime routes while piecing together this gorgeous 28x20 inch heirloom masterpiece.',
    price: 649,
    selling_price: 649,
    mrp: 899,
    discountPercentage: 28,
    discount_percentage: 28,
    stock: 25,
    stock_quantity: 25,
    rating: 4.7,
    reviewCount: 33,
    is_featured: 0,
    is_bestseller: 0,
    is_new_arrival: 1,
    is_offer: 1,
    ageGroup: '12+',
    age_group: '12+',
    images: [
      { id: 1501, url: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?auto=format&fit=crop&w=800&q=80', alt: '1000 Piece Jigsaw Puzzle', isPrimary: true }
    ]
  },
  {
    id: 16,
    slug: 'pocket-pop-it-fidget-game-console',
    name: 'Quick-Push Light-Up Electronic Fidget Game Console',
    sku: 'FDG-PUSH-01',
    category_id: 10,
    category_name: 'Baby & Toddler Sensory',
    brand_id: 5,
    brand_name: 'Funskool',
    short_description: 'Addictive speed puzzle sensory game with 4 game modes, sound effects & lights.',
    description: 'Pocket-sized fun that reduces screen time! Push the popping bubbles as fast as they illuminate. Features Mission, Memory, Scoring, and Multiplayer modes.',
    price: 399,
    selling_price: 399,
    mrp: 699,
    discountPercentage: 43,
    discount_percentage: 43,
    stock: 50,
    stock_quantity: 50,
    rating: 4.9,
    reviewCount: 110,
    is_featured: 1,
    is_bestseller: 1,
    is_new_arrival: 1,
    is_offer: 1,
    ageGroup: '3-5',
    age_group: '3-5',
    images: [
      { id: 1601, url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80', image_url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80', alt: 'Electronic Fidget Game', isPrimary: true }
    ]
  }
];

export const MOCK_REVIEWS = [
  {
    id: 1,
    customer_name: 'Priyanka Sharma',
    city: 'New Delhi',
    rating: 5,
    date: '2 days ago',
    comment: 'The 360° Stunt RC Car is insane! My 7-year-old hasn’t touched his tablet for 3 days. Super sturdy, survived several stair tumbles!',
    product: '360° Stunt Tumbler RC Car',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80'
  },
  {
    id: 2,
    customer_name: 'Rajesh Nair',
    city: 'Bengaluru',
    rating: 5,
    date: '5 days ago',
    comment: 'Ordered the 12-in-1 Solar Robotics kit. Exceptional build quality. WhatsApp customer support guided us with tracking immediately.',
    product: '12-in-1 STEM Solar Robot Kit',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80'
  },
  {
    id: 3,
    customer_name: 'Simran Kaur',
    city: 'Chandigarh',
    rating: 5,
    date: '1 week ago',
    comment: 'Original LEGO set delivered in spotless packaging to Chandigarh within 48 hours. Best toy store experience in India!',
    product: 'LEGO Classic Creative Bricks',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80'
  }
];
